language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
  allow_failures:
    - os: linux

addons:
  apt:
    update: true

r_binary_packages:
  - magrittr
  - lazyeval
  - mime
  - curl
  - openssl
  - R6
  - jsonlite
  - httr
  - crayon
  - reshape2
  - data.table
  - coda
  - testthat
  - digest
  - praise
  - lubridate

r_packages:
  - R.rsp

r_github_pacakges:
  - r-lib/covr

apt_packages:
  - libxml2-dev
  - libnetcdf-dev
  - libhdf5-dev

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      LINUXBREW="/home/linuxbrew/.linuxbrew";
      export PATH="$LINUXBREW/bin:$LINUXBREW/sbin/$PATH";
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)";
      brew install libssh2;
      brew install libbi;
    fi
  - R -e "install.packages('ncdf4')"
