language: r
cache: packages

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
  allow_failures:
    - os: linux

r_binary_packages:
  - magrittr
  - lazyeval
  - mime
  - curl
  - openssl
  - R6
  - jsonlite
  - httr
  - crayon
  - reshape2
  - data.table
  - coda
  - testthat
  - digest
  - praise
  - knitr
  - xml2
  - ncdf4
  - R.rsp
  - roxygen2
  - scales
  - coda
  - GGally

apt_packages:
  - libblas-dev
  - liblapack-dev
  - libqrupdate-dev
  - libboost-all-dev
  - libgsl0-dev
  - libnetcdf-dev
  - autoconf
  - automake

r_github_pacakges:
  - r-lib/covr

brew_packages:
  - libbi

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      curl -fLo /tmp/thrust-1.8.2.zip https://github.com/thrust/thrust/releases/download/1.8.2/thrust-1.8.2.zip;
      unzip /tmp/thrust-1.8.2.zip;
      sudo mv thrust /usr/local/include;
      curl -fLo /tmp/LibBi.tar.gz https://github.com/lawmurray/LibBi/archive/stable.tar.gz;
      tar xzf /tmp/LibBi.tar.gz -C ~;
      pushd ~/LibBi-stable;
      cpanm --quiet --installdeps --notest --sudo .;
      cpanm --quiet --sudo .;
      popd;
    fi
  - Rscript -e 'devtools::install_github("sbfnk/rbi")'
